### PR TITLE
build.sh: automatically log builds and repo syncs

### PR DESCRIPTION
**Pull request by mikecriggs**
This will allow people building PA to check their full terminal output in '$DIR/logs' to pin-point errors.

### CODE REVIEW

**Comment by mikecriggs** [comment]
Just an idea. No need to commit if it seems a bit too unnecessary.

**Comment by Urinophoria** [comment]
I like this (as a noob) I think it seems really helpful

**Comment by Anu6is** [comment]
As this project is being tracked on gerrit, this should be submitted there.

**Comment by mikecriggs** [comment]
Andre just told me a few days ago. I'll be taking a couple minutes to rewrite it to automatically create the directories and such. I'll submit it to gerrit afterward. I'll close the pull request :).

**Pull request closed without merging**
